### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by faraco**
* added download badge

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks

**Comment by faraco** [comment]
:D

**Comment by zoffixznet** [comment]
FWIW, now that I look at it, it's kinda weird. It reads zero downloads, suggesting it's not a popular package, but no one is meant to download anything anyway, since the correct way to install it is using `zef` or other Perl 6 package manager.

I may end up removing it in the future. Sorry.

**Comment by AlexDaniel** [comment]
Yes.

Also, why put a third-party tracking bug on your own page? Doesn't make any sense…

**Comment by faraco** [comment]
yea, I realized that. It's pointless.

**Pull request merged**
